# Generated by Django 4.1.6 on 2023-02-04 12:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0004_alter_photo_mpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbuser',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passes',
            name='activ',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FT', 'пешком'), ('SK', 'лыжи'), ('CN', 'катамаран'), ('KK', 'байдарка'), ('RT', 'плот'), ('RR', 'сплав'), ('BC', 'велосипед'), ('AU', 'автомобиль'), ('MB', 'мотоцикл'), ('SA', 'парус'), ('HR', 'верхом')], max_length=2), blank=True, size=11),
        ),
        migrations.AlterField(
            model_name='passes',
            name='autumn_dif',
            field=models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б'), ('4A', '4А'), ('4B', '4Б'), ('5A', '5А'), ('5B', '5Б'), ('6A', '6А'), ('6B', '6Б')], max_length=2),
        ),
        migrations.AlterField(
            model_name='passes',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passes',
            name='spring_dif',
            field=models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б'), ('4A', '4А'), ('4B', '4Б'), ('5A', '5А'), ('5B', '5Б'), ('6A', '6А'), ('6B', '6Б')], max_length=2),
        ),
        migrations.AlterField(
            model_name='passes',
            name='summer_dif',
            field=models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б'), ('4A', '4А'), ('4B', '4Б'), ('5A', '5А'), ('5B', '5Б'), ('6A', '6А'), ('6B', '6Б')], max_length=2),
        ),
        migrations.AlterField(
            model_name='passes',
            name='winter_dif',
            field=models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б'), ('4A', '4А'), ('4B', '4Б'), ('5A', '5А'), ('5B', '5Б'), ('6A', '6А'), ('6B', '6Б')], max_length=2),
        ),
    ]
