# Generated by Django 4.1.6 on 2023-02-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0005_alter_dbuser_name_alter_dbuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='mpass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='baza.passes'),
        ),
    ]
