# Generated by Django 4.1.6 on 2023-02-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0006_alter_photo_mpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passes',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='baza.localzones'),
        ),
    ]
