# Generated by Django 4.1.6 on 2023-02-07 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0007_alter_passes_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passes',
            name='activ',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FT', 'пешком'), ('SK', 'лыжи'), ('CN', 'катамаран'), ('KK', 'байдарка'), ('RT', 'плот'), ('RR', 'сплав'), ('BC', 'велосипед'), ('AU', 'автомобиль'), ('MB', 'мотоцикл'), ('SA', 'парус'), ('HR', 'верхом')], max_length=2), blank=True, null=True, size=11),
        ),
    ]
